"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path");
const src=fs.readFileSync(path.join(__dirname,"..","index.html"),"utf8");
const fn=name=>{const a=src.indexOf("function "+name+"("),b=src.indexOf("\nfunction ",a+10);assert.ok(a>=0&&b>a,name);return src.slice(a,b)};
const clean=fn("rbCleanGeneratedHtml");
assert.match(clean,/data-\(\?:pm\|mce\|slate\|gramm\|cke\|lexical\|prosemirror\)/);
assert.match(clean,/contenteditable\$/);
assert.match(clean,/spellcheck\$/);
for(const cls of ["rbtools-caption","rbtools-image","rbtools-main-image","rbtools-heading","rbtools-embed"])assert.ok(clean.includes('"'+cls+'"'));
assert.match(clean,/querySelectorAll\("h1,h2,h3,h4,h5,h6"\)/);
assert.match(clean,/text-align\\s\*:\\s\*\(left\|center\|right\|justify\)/);
assert.match(clean,/el\.setAttribute\("style","text-align: "\+align\+";"\)/);
assert.match(clean,/querySelectorAll\("span"\)/);
assert.match(clean,/div > p/);
assert.match(clean,/meaningful\.length===1&&meaningful\[0\]===p/);
assert.match(fn("adminNormalizeInlineHtml"),/rbCleanGeneratedHtml\(html\)/);
assert.match(fn("adminNormalizeInlineHtml"),/rbCleanGeneratedHtml\(t\.innerHTML\)/);
assert.match(fn("adminGenerateHtml"),/rbGet\("adminOutput"\)\.value=rbCleanGeneratedHtml\(out\)/);
assert.match(fn("doConvertArticle"),/rbCleanGeneratedHtml\(convertArticleInput/);
assert.match(fn("doConvertBox"),/rbCleanGeneratedHtml/);
assert.match(fn("doConvertTable"),/rbCleanGeneratedHtml/);
assert.match(fn("doConvertCollection"),/rbCleanGeneratedHtml/);
assert.match(fn("renderImagesOutput"),/rbCleanGeneratedHtml/);
assert.match(src,/#rbtools-app \.admin-dropzone\{height:7px;margin:0/);
assert.match(src,/#rbtools-app \.admin-block\{[^}]*padding:5px 44px 5px 7px;margin:0/);
assert.ok(src.includes('const RBTOOLS_VERSION="pages-v57"'));
console.log("Conservative HTML cleanup + compact WYSIWYG spacing: PASS");