"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path");
const src=fs.readFileSync(path.join(__dirname,"..","index.html"),"utf8");
const fn=name=>{const a=src.indexOf("function "+name+"("),b=src.indexOf("\nfunction ",a+10);assert.ok(a>=0&&b>a,name);return src.slice(a,b)};
const templ=fn("adminTemplateBlocks");
assert.match(templ,/if\(type==="news"\)\{\s*const out=\[\];/s);
assert.doesNotMatch(templ,/Még kell:<ul>/);
const apply=fn("adminApplyTemplate");
assert.match(apply,/adminLeadHtml='Lead szövege\.<br \/><br \/>Még kell:<ul><li>Hír X \(by MM\)<\/li><li>Hír X \(by MM\)<\/li><\/ul>'/);
const recover=fn("adminRecoverNewsPrelude");
assert.match(recover,/adminComparableText\(nodes\[i\]\.textContent\)===comparableTitle|candidateComparable===comparableTitle/);
assert.match(recover,/Hétvégi gyors\\b/);
assert.match(recover,/adminLeadHtml=current\?\(current\+"<br \/><br \/>"\+checklist\):checklist/);
assert.match(recover,/adminNewsChecklistNode\(nodes\[i\]\)/);
const load=fn("adminLoadExistingHtml");
assert.match(load,/adminRecoverNewsPrelude\(nodes,rbGet\("adminTitle"\)\.value\)/);
assert.match(load,/const promote=!!postIntro&&!looksLikeNews/);
const gen=fn("adminGenerateHtml");
assert.match(gen,/<strong>'\+topHtml\+'<\/strong><\/div>\\n<br \/>\\n<!--more-->/);
assert.ok(src.includes('const RBTOOLS_VERSION="pages-v54"'));
console.log("#nyúz title stays in Blogger field; lead + checklist stay together before more: PASS");