"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path");
const src=fs.readFileSync(path.join(__dirname,"..","index.html"),"utf8");
const fn=name=>{const a=src.indexOf("function "+name+"("),b=src.indexOf("\nfunction ",a+10);assert.ok(a>=0&&b>a,name);return src.slice(a,b)};
assert.match(src,/#rbtools-app \.admin-canvas\{margin-top:12px;background:#fff;color:#111;border:/);
assert.doesNotMatch(src,/#rbtools-app \.admin-canvas\{[^}]*font-family:Inter/);
assert.match(src,/#rbtools-app \.admin-paper-title\{font:700 27px\/1\.2 Inter,/);
assert.match(src,/#rbtools-app \.admin-p\{text-align:justify;font:16px\/1\.55 Inter,/);
const templ=fn("adminTemplateBlocks");
assert.match(templ,/if\(type==="news"\)/);
assert.match(templ,/out\.push\(h\("Hír cím"\),p\("<strong>Város \| Ország<\/strong> – Hír szövege"\),hr\(\)\)/);
const build=fn("adminBuildFromSource");
assert.match(build,/contentType==="news"\?"news":"general"/);
assert.match(build,/contentType==="news"\?newsBodyToHtml\(body\):bodyToHtml\(body\)/);
const load=fn("adminLoadExistingHtml");
assert.match(load,/\^Hétvégi gyors\\b/i);
assert.match(load,/newsMode&&centered&&onlyStrong&&!looksLikeNewsBody/);
assert.match(load,/type:"h3".*align:"center"/s);
assert.match(load,/align:newsMode\?"justify":adminAlignFromNode/);
assert.match(load,/if\(rbGet\("adminContentType"\)\.value==="news"\)adminRepairNewsBlocks\(\)/);
assert.match(src,/function adminNormalizeNewsParagraphHtml\(/);
assert.match(src,/function adminRepairNewsBlocks\(/);
assert.match(src,/function adminNewsTitleBefore\(/);
assert.match(src,/if\(candidate\.type==="hr"\)return null/);
assert.match(src,/\["image","iframe","raw"\]\.includes\(candidate\.type\)/);
assert.match(src,/placeholder:"Hír cím"/);
assert.match(src,/missingNewsTitle:true/);
assert.match(src,/if\(!headingHtml\.trim\(\)\)return ""/);
const normalize=fn("adminNormalizeNewsParagraphHtml");
const normalizeNews=new Function(normalize+"return adminNormalizeNewsParagraphHtml;")();
assert.equal(normalizeNews("<strong>Wien [Bécs] | Ausztria – Teljes törzsszöveg <a href=\"#\">linkkel</a>.</strong>"),"<strong>Wien [Bécs] | Ausztria</strong> – Teljes törzsszöveg <a href=\"#\">linkkel</a>.");
assert.equal(normalizeNews("<strong>Csak félkövér cím, nincs helymegjelölés</strong>"),"<strong>Csak félkövér cím, nincs helymegjelölés</strong>");

assert.match(src,/function adminNewsInlineFragmentHtml\(/);
assert.match(src,/function adminLooksLikeNewsBodyHtml\(/);
assert.match(src,/function adminRepairMalformedNewsHeadings\(/);
assert.match(load,/adminRepairMalformedNewsHeadings\(tpl\.content\)/);
assert.match(load,/recoveredHeadings/);
assert.match(load,/postText===title&&title&&\(!hasMore\|\|looksLikeNews\)/);
assert.match(load,/adminNewsInlineFragmentHtml\(n\)/);
assert.match(load,/adminRepairMalformedNewsHeadings\(temp\)/);
const htmlToBlocks=fn("adminHtmlToBlocks");
assert.match(htmlToBlocks,/adminNewsInlineFragmentHtml\(node\)/);
assert.match(htmlToBlocks,/adminRepairMalformedNewsHeadings\(temp\)/);
assert.ok(src.includes('const RBTOOLS_VERSION="pages-v59"'));
console.log("v40 editor typography + #nyúz titles and justified bodies: PASS");