"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path");
const src=fs.readFileSync(path.join(__dirname,"..","index.html"),"utf8");
const fn=name=>{const a=src.indexOf("function "+name+"("),b=src.indexOf("\nfunction ",a+10);assert.ok(a>=0&&b>a,name);return src.slice(a,b)};
assert.match(src,/#rbtools-app \.admin-canvas\{margin-top:12px;background:#fff;color:#111;border:/);
assert.doesNotMatch(src,/#rbtools-app \.admin-canvas\{[^}]*font-family:Inter/);
assert.match(src,/#rbtools-app \.admin-paper-title\{font:700 27px\/1\.2 Arial,Helvetica,sans-serif/);
assert.match(src,/#rbtools-app \.admin-p\{text-align:justify;font:16px\/1\.55 Arial,Helvetica,sans-serif/);
const templ=fn("adminTemplateBlocks");
assert.match(templ,/if\(type==="news"\)/);
assert.match(templ,/out\.push\(h\("Hír cím"\),p\("<strong>Város \| Ország<\/strong> – Hír szövege"\),hr\(\)\)/);
const build=fn("adminBuildFromSource");
assert.match(build,/contentType==="news"\?"news":"general"/);
assert.match(build,/contentType==="news"\?newsBodyToHtml\(body\):bodyToHtml\(body\)/);
const load=fn("adminLoadExistingHtml");
assert.match(load,/\^Hétvégi gyors\\b/i);
assert.match(load,/newsMode&&centered&&onlyStrong&&!looksLikeNewsBody/);
assert.match(load,/type:"h3".*align:"center"/s);
assert.match(load,/align:newsMode\?"justify":adminAlignFromNode/);
assert.match(load,/if\(rbGet\("adminContentType"\)\.value==="news"\)\{\s*adminBlocks\.forEach\(block=>\{if\(block\.type==="p"\)block\.align="justify";\}\)/s);
assert.ok(src.includes('const RBTOOLS_VERSION="pages-v45"'));
console.log("v40 editor typography + #nyúz titles and justified bodies: PASS");