"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path");
const root=path.join(__dirname,"..");
const index=fs.readFileSync(path.join(root,"index.html"),"utf8");
const privacy=fs.readFileSync(path.join(root,"privacy.html"),"utf8");
const terms=fs.readFileSync(path.join(root,"terms.html"),"utf8");
const homepageMarkup=index.slice(0,index.indexOf("<style>"));
assert.match(homepageMarkup,/id="rbtools-siteFooter"/);
assert.match(homepageMarkup,/href="\/privacy\.html">Adatkezelési tájékoztató<\/a>/);
assert.match(homepageMarkup,/href="\/terms\.html">Használati feltételek<\/a>/);
assert.match(homepageMarkup,/class="admin-privacy-notice"/);
assert.match(homepageMarkup,/Google-adatok és adatvédelem/);
assert.match(homepageMarkup,/OAuth hozzáférési token csak az aktuális böngészőmunkamenet memóriájában marad/);
assert.match(privacy,/https:\/\/www\.googleapis\.com\/auth\/blogger/);
assert.match(privacy,/Google API Services User Data Policy/);
assert.match(privacy,/Limited Use/);
assert.match(privacy,/hogyan használjuk az adatokat/i);
assert.match(privacy,/Tárolás a böngészőben/);
assert.match(privacy,/Adattovábbítás/);
assert.match(terms,/href="\/privacy\.html"/);
assert.ok(index.includes('const RBTOOLS_VERSION="pages-v57"'));
console.log("Google OAuth homepage/privacy production-readiness links and disclosures: PASS");
