"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path");
const root=path.join(__dirname,"..");
const index=fs.readFileSync(path.join(root,"index.html"),"utf8");
const privacy=fs.readFileSync(path.join(root,"privacy.html"),"utf8");
const terms=fs.readFileSync(path.join(root,"terms.html"),"utf8");
const footer=index.match(/<footer id="rbtools-siteFooter"[\s\S]*?<\/footer>/)?.[0]||"";
assert.match(footer,/href="\/privacy\.html">Adatkezelési tájékoztató<\/a>/);
assert.match(footer,/href="\/terms\.html">Használati feltételek<\/a>/);
const notice=index.match(/<div class="admin-privacy-notice"[\s\S]*?<\/div>/)?.[0]||"";
assert.match(notice,/Google-adatok és adatvédelem/);
assert.match(notice,/OAuth hozzáférési token csak az aktuális böngészőmunkamenet memóriájában marad/);
assert.match(privacy,/https:\/\/www\.googleapis\.com\/auth\/blogger/);
assert.match(privacy,/Google API Services User Data Policy/);
assert.match(privacy,/Limited Use/);
assert.match(privacy,/hogyan használjuk az adatokat/i);
assert.match(privacy,/Tárolás a böngészőben/);
assert.match(privacy,/Adattovábbítás/);
assert.match(terms,/href="\/privacy\.html"/);
assert.ok(index.includes('const RBTOOLS_VERSION="pages-v59"'));
console.log("Google OAuth homepage/privacy production-readiness links and disclosures: PASS");
