"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path");
const src=fs.readFileSync(path.join(__dirname,"..","index.html"),"utf8");
const fn=name=>{const a=src.indexOf("function "+name+"("),b=src.indexOf("\nfunction ",a+10);assert.ok(a>=0&&b>a,name);return src.slice(a,b)};
assert.ok(src.includes("＋ Új bekezdésblokk"));
assert.match(src,/Enter = új önálló/);
assert.match(src,/Shift\+Enter = sortörés/);
assert.match(src,/BR ✓ \/ BR ×/);
assert.match(fn("adminNodeHasBreakAfter"),/tagName==="BR"/);
assert.match(fn("adminInsertParagraphAfter"),/breakAfter:breakAfter!==false/);
assert.match(fn("adminSplitTextBlockAtCaret"),/block\.breakAfter=true/);
assert.match(fn("adminSplitTextBlockAtCaret"),/adminInsertParagraphAfter\(index/);
assert.match(fn("adminTrackEditable"),/e\.key==="Enter"/);
assert.match(fn("adminTrackEditable"),/e\.shiftKey/);
assert.match(fn("adminTrackEditable"),/insertLineBreak/);
assert.match(fn("adminBlockControls"),/BR ×/);
assert.match(fn("adminBlockControls"),/BR ✓/);
assert.match(fn("adminBlockControls"),/block\.breakAfter=block\.breakAfter===false/);
assert.ok(fn("adminBlockHtml").includes('b.breakAfter===false?"":"\\n<br />"'));
assert.match(fn("adminHtmlToBlocks"),/breakAfter:adminNodeHasBreakAfter\(nodes,i\)/);
assert.match(fn("adminLoadExistingHtml"),/breakAfter:adminNodeHasBreakAfter\(nodes,i\)/);
assert.ok(src.includes('const RBTOOLS_VERSION="pages-v59"'));
console.log("Enter paragraph split + per-paragraph BR spacing: PASS");